### PR TITLE
Add My language

### PR DESCRIPTION
**Pull request by xnisha-verma**
coffeescript's code #1

### CODE REVIEW

**Comment by Brijeshthummar02** [comment]
@xnisha-verma any update?

**Comment by xnisha-verma** [comment]
> @xnisha-verma any update?
what updates i needed to give?

**Comment by Brijeshthummar02** [comment]
@xnisha-verma  requested changes update it according to it, asked you to remove hello.coffee file and just let Coffee.coffee file, also add that file in README.md

**Comment by xnisha-verma** [comment]
> @xnisha-verma requested changes update it according to it, asked you to remove hello.coffee file and just let Coffee.coffee file, also add that file in README.md
> 
> Once you do it I'll merge the pr.
all updates are done :)

**Pull request merged**
